---
- name: set MariaDB repository for {{ ansible_distribution }}
  include: "{{ ansible_distribution }}.yml"

- name: enable service
  service: name=mysql state=started enabled=yes

- name: set root password
  mysql_user:
    name: root
    host: localhost
    password: "{{ mariadb_root_password }}"

- name: put .my.cnf
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
