---
- name: import the signing key
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=0xcbcb082a1bb943db

- name: set MariaDB on apt repository
  template: src=mariadb.list.j2 dest=/etc/apt/sources.list.d/mariadb.list owner=root group=root mode=0644

- name: install mariadb-server and python-mysqldb
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - mariadb-server
    - python-mysqldb
