---
- name: systemctl stop firewalld
  command: systemctl stop firewalld
  ignore_errors: yes

- name: systemctl disable firewalld
  command: systemctl disable firewalld
  ignore_errors: yes

- name: install libselinux-python
  yum: name=libselinux-python state=present

- name: check SELinux status
  command: getenforce
  register: selinux_result
  ignore_errors: yes

- name: disable SELinux
  selinux: state=disabled
  when: selinux_result.stdout != "Disabled"
  ignore_errors: yes

- name: install dependency modules
  yum: name={{ item }} state=present
  with_items:
    - sudo
    - gcc
    - kernel-devel
    - perl
    - tcl
    - make
    - wget
    - tar
    - ruby
    - git
    - vim
