---
- name: stop iptables
  service: name=iptables state=stopped enabled=no
  ignore_errors: yes

- name: stop ip6tables
  service: name=ip6tables state=stopped enabled=no
  ignore_errors: yes

- name: install libselinux-python
  yum: name=libselinux-python state=present

- name: check SELinux status
  command: getenforce
  register: selinux_result
  ignore_errors: yes

- name: disable SELinux
  selinux: state=disabled
  when: selinux_result.stdout != "Disabled"
  ignore_errors: yes
