---
- name: set Cloudera on apt repository
  template: src=cloudera.list.j2 dest=/etc/apt/sources.list.d/cloudera.list owner=root group=root mode=0644

- name: additional step for trusty
  template: src=cloudera.pref.j2 dest=/etc/apt/preferences.d/cloudera.pref owner=root group=root mode=0644
  when: ansible_distribution_release == "trusty"

- name: add the Cloudera Repository Key (optional)
  apt_key: state=present url=https://archive.cloudera.com/cdh5/ubuntu/{{ ansible_distribution_release }}/amd64/cdh/archive.key
