---
- hosts: cdh5-pseudo
  become: yes
  roles:
    - common
  tags:
    - common

- hosts: cdh5-pseudo
  become: yes
  roles:
    - oracle_jdk
  tags:
    - oracle_jdk

- hosts: cdh5-pseudo
  become: yes
  roles:
    - cdh_common
  tags:
    - hadoop

- hosts: cdh5-pseudo
  become: yes
  roles:
    - zookeeper
  tags:
    - zookeeper
