---
- hosts: cdh5-pseudo
  become: yes
  roles:
    - common
  tags:
    - common

- hosts: cdh5-pseudo
  become: yes
  roles:
    - oracle_jdk
  tags:
    - oracle_jdk

- hosts: cdh5-pseudo
  become: yes
  roles:
    - cdh_common
  tags:
    - cdh_common

- hosts: cdh5-pseudo
  become: yes
  roles:
    - hadoop
  tags:
    - hadoop

- hosts: cdh5-pseudo
  become: yes
  roles:
    - zookeeper
  tags:
    - zookeeper

- hosts: cdh5-pseudo
  become: yes
  roles:
    - hbase
  tags:
    - hbase

- hosts: cdh5-pseudo
  become: yes
  roles:
    - mariadb
  tags:
    - mariadb

- hosts: cdh5-pseudo
  become: yes
  roles:
    - mysql_connector_java
  tags:
    - mysql_connector_java

- hosts: cdh5-pseudo
  become: yes
  roles:
    - hive
  tags:
    - hive

- hosts: cdh5-pseudo
  become: yes
  roles:
    - spark
  tags:
    - spark
